replicaCount: 1
revisionHistoryLimit: 3
image:
  repository: ghcr.io/department-of-veterans-affairs/lighthouse-backstage
  pullPolicy: Always
  tag: KL123
containers:
  frontend:
    name: http
    port: 3000
    livenessProbe:
      initialDelaySeconds: 5
      path: /healthcheck
    readinessProbe:
      initialDelaySeconds: 5
      path: /healthcheck
  backend:
    name: port-2
    port: 7000
    livenessProbe:
      initialDelaySeconds: 5
      path: /healthcheck
    readinessProbe:
      initialDelaySeconds: 5
      path: /healthcheck
  postgres: null
imagePullSecrets: []
frontend:
  name: frontend
nameOverride: ''
fullnameOverride: ''
secrets:
  DOCKERCONFIGJSON: ${DOCKERCONFIGJSON}
  GH_TOKEN: ${GH_TOKEN}
  BASE_URL: ${BASE_URL}
  BACKEND_PORT: ${BACKEND_PORT}
  HOST: ${HOST}
  GATEWAY: ${GATEWAY}
  GH_CLIENT_ID: ${GH_CLIENT_ID}
  GH_CLIENT_SECRET: ${GH_CLIENT_SECRET}
  nonprod: ${nonprod}
serviceAccount:
  create: true
  annotations: {}
  name: ''
podAnnotations:
  namespace: lighthouse-bandicoot-dev
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
virtualService:
  destination:
    frontend:
      port: 8000
    backend:
      port: 7000
ingress:
  enabled: false
resources:
  limits:
    cpu: '0.5'
    memory: 500Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
