# This is a basic workflow to help you get started with Actions

name: Create values file

# Controls when the workflow will run
on:
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  create-values-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update Image Version in the related HelmChart values.dev.yaml
        uses: mikefarah/yq@master
        with:
          cmd: yq e -i '.image.tag = "KL123"' 'dev.values.yaml'
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update dev.values.yml file
          branch: main
