# This is a basic workflow to help you get started with Actions

name: Chart release

# Controls when the workflow will run
on:
  push:
  # Allows external webhook trigger
  repository_dispatch:
    types: [dev]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: list github event contents
        run: |
          echo "${{ github.event.client_payload }}"
          echo "${{ github.event.client_payload.sha }}"
